/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    QBanner: typeof import("quasar")["QBanner"];
    QBtn: typeof import("quasar")["QBtn"];
    QCard: typeof import("quasar")["QCard"];
    QCardActions: typeof import("quasar")["QCardActions"];
    QCardSection: typeof import("quasar")["QCardSection"];
    QIcon: typeof import("quasar")["QIcon"];
    QInput: typeof import("quasar")["QInput"];
    QLayout: typeof import("quasar")["QLayout"];
    QPage: typeof import("quasar")["QPage"];
    QPageContainer: typeof import("quasar")["QPageContainer"];
    QTable: typeof import("quasar")["QTable"];
    QTd: typeof import("quasar")["QTd"];
    QTooltip: typeof import("quasar")["QTooltip"];
    RemoteDataTable: typeof import("./components/RemoteDataTable.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
  }
}
